---
abstract: 'Read and prepare parsing of file (or glob) data'
author:
  - 'Torbjørn Lindahl <torbjorn.lindahl@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4204, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: File-Parser-Role
provides:
  File::Parser::Role:
    file: lib/File/Parser/Role.pm
    version: v0.2.0
recommends:
  IO::All: '0'
  Mojo::Path: '0'
  Path::Tiny: '0'
requires:
  IO::String: '1.08'
  Moo: '1.006001'
  Moo::Role: '1.006001'
  MooX::Aliases: '0.001'
  Pod::Coverage::Moose: '0.02'
  Test::Most: '0.34'
  Test::Output: '1.02'
  Test::Perl::Critic: '1.02'
  Test::Pod: '1.48'
  Test::Pod::Coverage: '1.08'
  Test::Warnings: '0.010'
resources:
  license: http://dev.perl.org/licenses/
version: v0.2.0
